### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by benregn** [marconi/django-quickstart#1]
What did you use to create the presentation?

**Comment by marconi** [comment]
I originally used keynote but I exported it to PDF so its viewable on all platforms.

**Comment by benregn** [comment]
Cool, are the code snippet highlighting built-in to Keynote?

**Comment by marconi** [comment]
Nope, I used pygments. :)

**Comment by benregn** [comment]
Interesting, how is that done? Would like to try it sometime.

**Comment by marconi** [comment]
I can't memorize how to do it but just look at the pygments docs. :)
